language: node_js

sudo: false

node_js:
  - "6.0"
  - "7.0"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - xvfb
      - g++-4.8

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache

before_install:
  - npm config set spin false

install:
  - npm install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

script:
  - npm test
